apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    # 镜像版本必须 <= 1.28.4 ，因为busybox上游代码有bug, 导致 nslookup 会失败
  - image: ${REGISTRY_DOMAIN}/${IMAGE_PATH}/busybox:1.28.4
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: OnFailure