kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: ${NODE_ADDRESS}
clusterDomain: ${DNS_DOMAIN}
clusterDNS:
  - ${DNS_SERVER_IP}
cgroupDriver: cgroupfs
resolvConf: "/etc/resolv.conf"
runtimeRequestTimeout: "15m"
failSwapOn: false
featureGates:
  RotateKubeletClientCertificate: true
  RotateKubeletServerCertificate: true
rotateCertificates: true
authentication:
  x509.clientCAFile: ${CERT_DIR}/ca.pem
# evictionHard:
#   memory.available: "1Gi"
#   nodefs.available: "5Gi"
#   imagefs.available: "5Gi"
# evictionMaxPodGracePeriod: 40
# evictionMinimumReclaim:
#   memory.available: "500Mi"
#   nodefs.available: "1Gi"
#   imagefs.available: "1Gi"
# evictionSoftGracePeriod:
#   memory.available: "30s"
#   nodefs.available: "2m"
#   imagefs.available: "2m"
# evictionSoft:
#   memory.available: "2Gi"
#   nodefs.available: "8Gi" 
#   imagefs.available: "8Gi"
# systemReserved:
#   cpu: "100m"
#   memory: "1G"